import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1788035555095 implements MigrationInterface {
    name = 'InitSchema1788035555095'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "probe" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_fcd86935af5ec48c6923761dc2b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('owner', 'admin')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "name" character varying NOT NULL DEFAULT '', "avatarUrl" character varying NOT NULL DEFAULT '', "role" "public"."users_role_enum" NOT NULL DEFAULT 'admin', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_users_single_owner" ON "users"  ("role") WHERE role = 'owner'`);
        await queryRunner.query(`CREATE TYPE "public"."invitations_role_enum" AS ENUM('owner', 'admin')`);
        await queryRunner.query(`CREATE TABLE "invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "role" "public"."invitations_role_enum" NOT NULL DEFAULT 'admin', "token" character varying NOT NULL, "used" boolean NOT NULL DEFAULT false, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdById" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e577dcf9bb6d084373ed3998509" UNIQUE ("token"), CONSTRAINT "PK_5dec98cfdfd562e4ad3648bbb07" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cd25692823f73a4e23d75edee0" ON "invitations"  ("email") WHERE used = false`);
        await queryRunner.query(`CREATE TABLE "knowledge_bases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "type" character varying NOT NULL DEFAULT 'document', "creatorId" uuid NOT NULL, "chunkingConfig" jsonb NOT NULL DEFAULT '{}'::jsonb, "embeddingModelId" uuid, "extractConfig" jsonb NOT NULL DEFAULT '{"enabled": true}'::jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b7da0ee578e15ebb6213465440d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_kb_pins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "kbId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9669f4186bc6f878b9f9a8db502" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8615fb2df4ed91855f27365305" ON "user_kb_pins"  ("userId", "kbId") `);
        await queryRunner.query(`CREATE TABLE "user_kb_favorites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "kbId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d1267a93c0546faaeb20a3bfe26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_13aeb1d5c4ee0c54e23696be3a" ON "user_kb_favorites"  ("userId", "kbId") `);
        await queryRunner.query(`CREATE TABLE "user_kb_recents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "kbId" uuid NOT NULL, "visitedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e9fcd59f68e60c62824e578a137" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_41cf6dd4f73cbbcb482eb69a19" ON "user_kb_recents"  ("userId", "visitedAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6a01aaf215e63e86f7eea0a7db" ON "user_kb_recents"  ("userId", "kbId") `);
        await queryRunner.query(`CREATE TABLE "chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kbId" uuid NOT NULL, "knowledgeId" uuid NOT NULL, "content" text NOT NULL, "sourceContent" text NOT NULL, "contentRevision" integer NOT NULL DEFAULT '0', "indexStatus" character varying NOT NULL DEFAULT 'processing', "embedding" vector(1024), "chunkIndex" integer NOT NULL DEFAULT '0', "startAt" integer NOT NULL DEFAULT '0', "endAt" integer NOT NULL DEFAULT '0', "preChunkId" uuid, "nextChunkId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a306e60b8fdf6e7de1be4be1e6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_chunks_kb_id" ON "chunks"  ("kbId") `);
        await queryRunner.query(`CREATE INDEX "idx_chunks_knowledge_index" ON "chunks"  ("knowledgeId", "chunkIndex") `);
        await queryRunner.query(`CREATE TABLE "chunk_revisions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "chunkId" uuid NOT NULL, "content" text NOT NULL, "revision" integer NOT NULL, "editorId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3df5c221a20717d66941beeda1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_chunk_revisions_chunk_revision" ON "chunk_revisions"  ("chunkId", "revision") `);
        await queryRunner.query(`CREATE TYPE "public"."knowledge_type_enum" AS ENUM('file', 'url', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."knowledge_status_enum" AS ENUM('pending', 'parsing', 'ready', 'failed')`);
        await queryRunner.query(`CREATE TABLE "knowledge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kbId" uuid NOT NULL, "folderId" uuid, "title" character varying NOT NULL, "type" "public"."knowledge_type_enum" NOT NULL DEFAULT 'file', "filePath" character varying NOT NULL DEFAULT '', "fileType" character varying NOT NULL DEFAULT '', "fileSize" integer NOT NULL DEFAULT '0', "sourceUrl" character varying NOT NULL DEFAULT '', "manualContent" text, "parsedText" text, "status" "public"."knowledge_status_enum" NOT NULL DEFAULT 'pending', "error" character varying NOT NULL DEFAULT '', "summary" text, "chunkCount" integer NOT NULL DEFAULT '0', "parserStages" jsonb NOT NULL DEFAULT '[]'::jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4159ba98b65a20a8d1f257bc514" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_knowledge_kb_id" ON "knowledge"  ("kbId") `);
        await queryRunner.query(`CREATE TABLE "knowledge_folders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kbId" uuid NOT NULL, "parentId" uuid, "name" character varying NOT NULL, "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0b1ce71bd9ded91d63e118e25a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_knowledge_folders_kb_name_unique_root" ON "knowledge_folders"  ("kbId", "name") WHERE "parentId" IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_knowledge_folders_kb_parent_name_unique" ON "knowledge_folders"  ("kbId", "parentId", "name") WHERE "parentId" IS NOT NULL`);
        await queryRunner.query(`CREATE INDEX "idx_knowledge_folders_kb_parent" ON "knowledge_folders"  ("kbId", "parentId") `);
        await queryRunner.query(`CREATE TABLE "knowledge_tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "knowledgeId" uuid NOT NULL, "tagId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6102a348a6f8ddebc49a0b96787" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_knowledge_tags_tag_id" ON "knowledge_tags"  ("tagId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_knowledge_tags_knowledge_tag_unique" ON "knowledge_tags"  ("knowledgeId", "tagId") `);
        await queryRunner.query(`CREATE TABLE "tags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kbId" uuid NOT NULL, "name" character varying NOT NULL, "color" character varying NOT NULL DEFAULT '#3b82f6', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7dc17249a1148a1970748eda99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_tags_kb_name_unique" ON "tags"  ("kbId", "name") `);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "title" character varying NOT NULL DEFAULT '新会话', "kbIds" jsonb NOT NULL DEFAULT '[]'::jsonb, "pinned" boolean NOT NULL DEFAULT false, "pinnedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_sessions_user_updated" ON "sessions"  ("userId", "updatedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."messages_role_enum" AS ENUM('user', 'assistant', 'system')`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "role" "public"."messages_role_enum" NOT NULL DEFAULT 'user', "content" text NOT NULL DEFAULT '', "reasoning" text, "references" jsonb NOT NULL DEFAULT '[]'::jsonb, "toolCalls" jsonb NOT NULL DEFAULT '[]'::jsonb, "ragStages" jsonb NOT NULL DEFAULT '[]'::jsonb, "attachments" jsonb NOT NULL DEFAULT '[]'::jsonb, "interrupted" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_messages_session_created" ON "messages"  ("sessionId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sessionId" uuid NOT NULL, "userId" uuid NOT NULL, "filename" character varying NOT NULL, "storedPath" character varying NOT NULL, "mimeType" character varying NOT NULL, "size" integer NOT NULL DEFAULT '0', "isImage" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_attachments_session_created" ON "attachments"  ("sessionId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."models_provider_enum" AS ENUM('openai-compatible', 'ollama')`);
        await queryRunner.query(`CREATE TYPE "public"."models_type_enum" AS ENUM('chat', 'embedding', 'rerank')`);
        await queryRunner.query(`CREATE TABLE "models" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "provider" "public"."models_provider_enum" NOT NULL, "baseUrl" character varying NOT NULL DEFAULT '', "apiKeyEncrypted" character varying NOT NULL DEFAULT '', "modelName" character varying NOT NULL, "type" "public"."models_type_enum" NOT NULL DEFAULT 'chat', "enabled" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "extraConfig" jsonb NOT NULL DEFAULT '{}'::jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ef9ed7160ea69013636466bf2d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_models_default_type" ON "models"  ("type") WHERE "isDefault" = true`);
        await queryRunner.query(`CREATE TYPE "public"."web_search_providers_provider_enum" AS ENUM('tavily', 'bing', 'google', 'baidu')`);
        await queryRunner.query(`CREATE TABLE "web_search_providers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "provider" "public"."web_search_providers_provider_enum" NOT NULL, "apiKeyEncrypted" character varying NOT NULL DEFAULT '', "baseUrl" character varying NOT NULL DEFAULT '', "searchEngineId" character varying, "enabled" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb52bbfabf7928da83550c375c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_web_search_providers_default" ON "web_search_providers"  ("isDefault") WHERE "isDefault" = true`);
        await queryRunner.query(`CREATE TABLE "organizations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "ownerId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6b031fcd0863e3f6b44230163f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."organization_members_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "organization_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orgId" uuid NOT NULL, "userId" uuid NOT NULL, "role" "public"."organization_members_role_enum" NOT NULL DEFAULT 'member', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c2b39d5d072886a4d9c8105eb9a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_org_members_user" ON "organization_members"  ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_org_members_org_user" ON "organization_members"  ("orgId", "userId") `);
        await queryRunner.query(`CREATE TYPE "public"."organization_invitations_role_enum" AS ENUM('owner', 'admin', 'member')`);
        await queryRunner.query(`CREATE TABLE "organization_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "orgId" uuid NOT NULL, "email" character varying NOT NULL, "role" "public"."organization_invitations_role_enum" NOT NULL DEFAULT 'member', "token" character varying NOT NULL, "used" boolean NOT NULL DEFAULT false, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdById" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_7dfa5b36a9305efc5b7e9f369a3" UNIQUE ("token"), CONSTRAINT "PK_f172f12b8a9ee6584b661f57e24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94f7162c51510b913b531fcee4" ON "organization_invitations"  ("orgId", "email") WHERE used = false`);
        await queryRunner.query(`CREATE TYPE "public"."knowledge_base_shares_permission_enum" AS ENUM('view', 'edit')`);
        await queryRunner.query(`CREATE TABLE "knowledge_base_shares" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kbId" uuid NOT NULL, "orgId" uuid NOT NULL, "permission" "public"."knowledge_base_shares_permission_enum" NOT NULL DEFAULT 'view', "createdById" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1ed63d8ded4d7e1a47f543c335c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_kb_shares_kb_org" ON "knowledge_base_shares"  ("kbId", "orgId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid, "action" character varying NOT NULL, "resourceType" character varying NOT NULL, "resourceId" uuid, "detail" jsonb NOT NULL DEFAULT '{}'::jsonb, "ip" character varying NOT NULL DEFAULT '', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_user" ON "audit_logs"  ("userId") `);
        await queryRunner.query(`CREATE INDEX "idx_audit_logs_action_created" ON "audit_logs"  ("action", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "platform_api_keys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "keyHash" character varying NOT NULL, "scopes" jsonb NOT NULL DEFAULT '[]'::jsonb, "enabled" boolean NOT NULL DEFAULT true, "lastUsedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_af3c86d0a36b9d85a8c81d29dc3" UNIQUE ("name"), CONSTRAINT "PK_8a45573cf02c348d47e5bb1441c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying NOT NULL, "value" jsonb NOT NULL DEFAULT '{}'::jsonb, "updatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_b1b5bc664526d375c94ce9ad43d" UNIQUE ("key"), CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP TABLE "platform_api_keys"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_action_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_audit_logs_user"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_kb_shares_kb_org"`);
        await queryRunner.query(`DROP TABLE "knowledge_base_shares"`);
        await queryRunner.query(`DROP TYPE "public"."knowledge_base_shares_permission_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94f7162c51510b913b531fcee4"`);
        await queryRunner.query(`DROP TABLE "organization_invitations"`);
        await queryRunner.query(`DROP TYPE "public"."organization_invitations_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_org_members_org_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_org_members_user"`);
        await queryRunner.query(`DROP TABLE "organization_members"`);
        await queryRunner.query(`DROP TYPE "public"."organization_members_role_enum"`);
        await queryRunner.query(`DROP TABLE "organizations"`);
        await queryRunner.query(`DROP INDEX "public"."idx_web_search_providers_default"`);
        await queryRunner.query(`DROP TABLE "web_search_providers"`);
        await queryRunner.query(`DROP TYPE "public"."web_search_providers_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_models_default_type"`);
        await queryRunner.query(`DROP TABLE "models"`);
        await queryRunner.query(`DROP TYPE "public"."models_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."models_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_attachments_session_created"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP INDEX "public"."idx_messages_session_created"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TYPE "public"."messages_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_sessions_user_updated"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_tags_kb_name_unique"`);
        await queryRunner.query(`DROP TABLE "tags"`);
        await queryRunner.query(`DROP INDEX "public"."idx_knowledge_tags_knowledge_tag_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_knowledge_tags_tag_id"`);
        await queryRunner.query(`DROP TABLE "knowledge_tags"`);
        await queryRunner.query(`DROP INDEX "public"."idx_knowledge_folders_kb_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_knowledge_folders_kb_parent_name_unique"`);
        await queryRunner.query(`DROP INDEX "public"."idx_knowledge_folders_kb_name_unique_root"`);
        await queryRunner.query(`DROP TABLE "knowledge_folders"`);
        await queryRunner.query(`DROP INDEX "public"."idx_knowledge_kb_id"`);
        await queryRunner.query(`DROP TABLE "knowledge"`);
        await queryRunner.query(`DROP TYPE "public"."knowledge_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."knowledge_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chunk_revisions_chunk_revision"`);
        await queryRunner.query(`DROP TABLE "chunk_revisions"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chunks_knowledge_index"`);
        await queryRunner.query(`DROP INDEX "public"."idx_chunks_kb_id"`);
        await queryRunner.query(`DROP TABLE "chunks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a01aaf215e63e86f7eea0a7db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41cf6dd4f73cbbcb482eb69a19"`);
        await queryRunner.query(`DROP TABLE "user_kb_recents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13aeb1d5c4ee0c54e23696be3a"`);
        await queryRunner.query(`DROP TABLE "user_kb_favorites"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8615fb2df4ed91855f27365305"`);
        await queryRunner.query(`DROP TABLE "user_kb_pins"`);
        await queryRunner.query(`DROP TABLE "knowledge_bases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd25692823f73a4e23d75edee0"`);
        await queryRunner.query(`DROP TABLE "invitations"`);
        await queryRunner.query(`DROP TYPE "public"."invitations_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_single_owner"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "probe"`);
    }

}
