// 会话标题生成处理器（Task 2.2）：消费 TITLE_QUEUE，载荷 { sessionId }。
// 流程：加载会话（不存在 → 记日志跳过 no-op——会话已删重试只会空转，与
// SummaryProcessor 的删除跳过同语义）→ 仅当标题为默认值「新会话」时生成
// （覆盖规则：手动重命名过的会话不覆盖；哨兵值边界见 DEFAULT_SESSION_TITLE
// 注释）→ 取首条用户消息内容（发送前截断到 TITLE_INPUT_MAX_LENGTH，防御
// 超长输入白烧 token，见下）→ 调 chatModel.chat([中文 system 提示 + 首条
// 消息]) → trim + 双字节安全截断 50 字（防御 LLM 超长输出；空结果保持原标题
// 不落库）→ 更新 title。
// 失败语义：attempts=2 + 指数退避（2s 起，入队时配置，见 MessageService
// enqueueTitle）——首次失败 BullMQ 重试一次，重试耗尽后仅记日志（标题缺失
// 不影响会话可用，非关键路径——不写失败状态，与 SummaryProcessor 同哲学）。
// TODO(Task 2.3): 接入真实 ChatModelService 后，生成质量由真实模型保证，
// 本处理器零改动（依赖注入经 CHAT_MODEL_SERVICE 令牌，见 model.module.ts）。
import { Inject, Injectable, Logger } from '@nestjs/common';
import { Processor, WorkerHost } from '@nestjs/bullmq';
import type { Job } from 'bullmq';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { CHAT_MODEL_SERVICE } from '../model/chat-model.interface.js';
import type { ChatModelService } from '../model/chat-model.interface.js';
import { clampSurrogateBoundary } from '../../common/unicode.js';
import { TITLE_QUEUE } from './chat-queue.constants.js';
import type { TitleJob } from './chat-queue.constants.js';
import { Message } from './message.entity.js';
import { Session } from './session.entity.js';

/** 会话默认标题：与 Session 实体 default / SessionService.create 的缺省值一致
 * （仅默认标题触发自动生成；手动重命名后 title !== 此值 → 不覆盖）。
 * 哨兵值边界（Task 2.2 质量审查整改登记）：用户手动把会话命名为「新会话」时
 * 与哨兵值撞车——首条消息仍会触发自动生成并覆盖该手动值。已知边界暂接受：
 * 彻底方案是 titleAutoGenerated 布尔列（生成与否显式化，不依赖字符串哨兵），
 * 但需动 Session 实体/迁移/全链路判定，当前场景过度设计，暂不做（Task 2.x
 * 有真实重命名需求时再评估）。 */
const DEFAULT_SESSION_TITLE = '新会话';

/** 标题最大长度（字符）：防御 LLM 超长输出的上限，超长时双字节安全截断
 * （clampSurrogateBoundary 保证不劈开 emoji 代理对，见 common/unicode.ts；
 * 单元测试断言用）。生成质量由 system 提示约束（10 字以内，见
 * TITLE_SYSTEM_PROMPT）——本常量只是防御上限：真实模型正常输出远小于 50，
 * 截断仅在模型异常超长时兜底（Task 2.3 换真实模型后保持，防失控输出）。 */
export const TITLE_MAX_LENGTH = 50;

/** 标题输入上限（字符）：首条用户消息发送给 LLM 前的截断阈值——防御语义
 * （Task 2.2 质量审查整改：此前全文透传无上限，真实 LLM 接入前按 token
 * 计费，超长消息白烧 token；标题生成只依赖提问开头内容，截断不损失信息）。
 * 双字节安全截断见 common/unicode.ts；单元测试断言用。 */
export const TITLE_INPUT_MAX_LENGTH = 2000;

/** 标题系统提示（固定中文：直接输出标题文本）。生成质量约束在提示内
 * （10 字以内）——prompt 约束质量、TITLE_MAX_LENGTH=50 仅为防御上限（见上）。 */
const TITLE_SYSTEM_PROMPT =
  '你是会话标题生成助手。根据用户的第一条提问，生成 10 个字以内的会话标题，只输出标题文本，不要引号或标点。';

@Processor(TITLE_QUEUE)
@Injectable()
export class TitleProcessor extends WorkerHost {
  private readonly logger = new Logger(TitleProcessor.name);

  constructor(
    @InjectRepository(Session)
    private readonly sessionRepo: Repository<Session>,
    @InjectRepository(Message)
    private readonly messageRepo: Repository<Message>,
    // 直接注入 ChatModelService（LLM 对话是标题生成的职责；Task 2.3 换真实
    // 实现时改 ModelModule 的 useClass，本处理器零改动）
    @Inject(CHAT_MODEL_SERVICE) private readonly chatModel: ChatModelService,
  ) {
    super();
  }

  /**
   * 消费 TITLE_QUEUE：会话存在性 → 覆盖规则（默认标题才生成）→ 首条用户消息
   * 内容 → 调 LLM 生成 → 截断 → 更新 title。
   * 返回 { titled }：是否实际更新了标题（调试/仪表盘展示用）。
   * 失败抛错触发 BullMQ 重试（attempts=2 + backoff 由入队配置决定）；
   * 重试耗尽后仅记日志（见文件头注释——标题非关键路径，不写失败状态）。
   */
  async process(job: Job<TitleJob>): Promise<{ titled: boolean }> {
    const { sessionId } = job.data;
    const session = await this.sessionRepo.findOne({
      where: { id: sessionId },
    });
    if (!session) {
      // 会话已删除（含级联清理）→ 标题无处可写；记日志跳过不抛错
      // （重试只会空转，与 SummaryProcessor 的删除跳过同一语义）
      this.logger.warn(
        `标题任务引用的会话不存在（可能已删除），跳过: ${sessionId}`,
      );
      return { titled: false };
    }
    // 覆盖规则：仅默认标题「新会话」触发自动生成——手动重命名过的会话
    // 不覆盖（title !== '新会话' → no-op，用户意图优先）
    if (session.title !== DEFAULT_SESSION_TITLE) {
      return { titled: false };
    }
    // 取首条用户消息内容（createdAt ASC + id 决胜键，与消息列表同排序语义；
    // 载荷最小化：payload 只带 sessionId，内容由 worker 从 DB 读取）
    const first = await this.messageRepo.findOne({
      where: { sessionId, role: 'user' },
      order: { createdAt: 'ASC', id: 'ASC' },
    });
    // 无消息/空白消息（异常中间态）→ no-op：没有可总结的提问内容
    if (!first || first.content.trim() === '') {
      return { titled: false };
    }
    // trim（空判定同语义，发送不留首尾空白）+ 输入上限截断（见下注释）
    const content = first.content.trim();
    try {
      // LLM 输入防御：首条消息全文可能极长（粘贴长文/OCR 结果），真实 LLM
      // 接入前按 token 计费，超长消息白烧 token。发送前双字节安全截断到
      // TITLE_INPUT_MAX_LENGTH（clampSurrogateBoundary 保证不劈开代理对，
      // 见 common/unicode.ts）；标题生成只依赖提问开头内容，截断不损失信息
      const input = content.slice(
        0,
        clampSurrogateBoundary(content, TITLE_INPUT_MAX_LENGTH),
      );
      const raw = await this.chatModel.chat(
        [
          { role: 'system', content: TITLE_SYSTEM_PROMPT },
          { role: 'user', content: input },
        ],
        undefined,
        session.userId,
      );
      // 输出防御：trim + 双字节安全截断到 TITLE_MAX_LENGTH——直接 slice 可能
      // 切在 emoji 代理对中间（标题变乱码，实测复现）；空结果保持原标题（不落库）
      const cleaned = raw.trim();
      const title = cleaned
        ? cleaned.slice(0, clampSurrogateBoundary(cleaned, TITLE_MAX_LENGTH))
        : session.title;
      if (title === session.title) {
        return { titled: false };
      }
      session.title = title;
      await this.sessionRepo.save(session);
      return { titled: true };
    } catch (err) {
      // 失败：仅记日志并抛错触发重试（attempts=2 + backoff 2s 由入队配置）。
      // 重试耗尽后 job 进 failed——标题缺失不影响会话使用（非关键路径）
      const message = err instanceof Error ? err.message : String(err);
      this.logger.warn(
        `标题生成失败（将按 backoff 重试，重试耗尽仅记日志）: ` +
          `${sessionId} - ${message}`,
      );
      throw err;
    }
  }
}
